---
title: "מטלה מסכמת- עקרונות יסוד של למידת מכונה"
author: "גלעד סרוסי ונעם גיל-עדי"
format: docx
lang: he
dir: rtl

editor: visual
---

## מבוא כללי

המחקר הנוכחי מהווה את החלק הראשון בפרויקט שמטרתו לבחון האם החפצה מינית של נשים עשויה לפגוע בגבר המבצע את ההחפצה. שלב זה מתמקד בעיקר בהיבטים קוגניטיביים ותפקודיים של הנבדקים ונערך באופן מקוון, תוך שימוש בגירוי ווידאו יחיד.

במסגרת המחקר, הנבדקים יתבקשו לצפות בסרטון עיוני באורך של כשלוש דקות, שבו מופיעה אישה אשר מעבירה תוכן דידקטי. בטרם הצפייה, הנבדקים יקבלו הנחיה כי יישאלו שאלות על תוכן הסרטון בהמשך ויוכלו לזכות בבונוס כספי בהתאם לרמת ההצלחה.

הווידאו מצולם בפריים רחב הכולל את גופה המלא של האישה. במהלך הצפייה, ינוטרו תנועות העיניים של הנבדקים באמצעות תוכנת RealEye. הנבדקים יקבלו הסבר לפיו הניטור נעשה כדי לוודא שהם מתמקדים בסרטון ולא מוסחים מגורמים חיצוניים.  

לאחר הצפייה בסרטון, הנבדקים יבצעו מטלת השלמת מילים, שבה יוצגו להם מילים חסרות אות אחת. חלק מהמילים מאפשרות השלמה למונחים בעלי קונוטציה מינית, בעוד אחרות נותרות ניטרליות. מטלה זו נועדה להעריך רמות אקטיבציה מינית סמויות.

לאחר מכן, הנבדקים ישיבו על שאלות הערכה שונות, הנוגעות בין היתר לתחושת הביטחון העצמי שלהם בביצוע מטלת הזיכרון, ציפיות למפגש עם האישה בווידאו, התרשמותם מהאישה (למשל, מידת האטרקטיביות, יכולת, אסרטיביות, וכדומה), ולתחושותיהם ביחס אליה (קירבה, חיבה ודמיון)

לבסוף,  הנבדקים יתבקשו למלא שאלון תכונתי הבוחן את הנטייה להחפצה (תוקף במחקר קודם), מידע דמוגרפי, וכן שאלות טכניות בנוגע לחוויית ההשתתפות.

מטרת עבודה זו היא לבחון האם ניתן לנבא את דפוסי ההסתכלות של נבדקים על סמך תשובותיהם של נבדקים בסקר. באופן ספציפי, האם ניתן לנבא משך ההתמקדות בחזה של השחקנית מתוך צפיות למפגש,התרשמותם ותחושותיהם.

על מנת לעשות זאת אני אשתמש ב-2 שיטות מידול שונות, השיטה הראשונה השיטת Booster לעצי רגרסיה

וושיטת המידול השניה תהינה random Forest.

המנבאים שלי יבחרו על ידי שיטת Best subset selection

לאחר מכן אבחן אלטרנטיקה של שימוש ב PLS על מנת לבחור את לצמצם את הממדים של המודל.

```{r}
#Packages loading:

library(tidymodels)
library(finetune)
library(baguette)
library(randomForest)
library(xgboost)


realeye <-read.csv("data/june_03/study-eye-tracking_study-bb4e80e4-c1e9-49dc-8438-79b88be60a9a-aoi-metrics-per-participant.csv")


```
